import {initializeApp} from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import {getAuth,onAuthStateChanged} from "https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import {getDatabase,ref,get,set,update} from "https://www.gstatic.com/firebasejs/12.19.0/firebase-database.js";
import {firebaseConfig} from "./firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getDatabase(app),$=id=>document.getElementById(id),ADMIN="ramkrishnadevinv.01@gmail.com";
let uid=null,room="",questions=[],loadedRoomData=null;
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));}
function msg(t,cls=""){ $("msg").textContent=t;$("msg").className="status "+cls; }
function isAdmin(u){return String(u?.email||"").toLowerCase()===ADMIN;}
async function access(u){if(!u)return false;if(isAdmin(u))return true;const s=await get(ref(db,`hosts/${u.uid}`));return s.exists()&&s.val()?.status==="approved";}
function resetEditor(){room="";loadedRoomData=null;questions=[];$("setup").classList.add("hidden");$("roomCode").textContent="------";$("questions").innerHTML="";}
function render(){const n=Math.max(1,Math.min(100,Number($("count").value||10)));questions=Array.from({length:n},(_,i)=>questions[i]||{text:"",options:{A:"",B:"",C:"",D:""},correct:"A"});$("questions").innerHTML=questions.map((q,i)=>`<div class="qbox"><h3>Question ${i+1}</h3><div class="field"><label>Question *</label><textarea id="q_${i}" rows="3" style="width:100%;box-sizing:border-box">${esc(q.text)}</textarea></div><div class="qgrid"><div class="field"><label>A *</label><input id="a_${i}" value="${esc(q.options?.A)}"></div><div class="field"><label>B *</label><input id="b_${i}" value="${esc(q.options?.B)}"></div><div class="field"><label>C *</label><input id="c_${i}" value="${esc(q.options?.C)}"></div><div class="field"><label>D *</label><input id="d_${i}" value="${esc(q.options?.D)}"></div><div class="field"><label>Correct Answer *</label><select id="cans_${i}"><option>A</option><option>B</option><option>C</option><option>D</option></select></div></div></div>`).join("");questions.forEach((q,i)=>$("cans_"+i).value=q.correct||"A");}
function collect(){return questions.map((_,i)=>({text:$("q_"+i).value.trim(),options:{A:$("a_"+i).value.trim(),B:$("b_"+i).value.trim(),C:$("c_"+i).value.trim(),D:$("d_"+i).value.trim()},correct:$("cans_"+i).value}));}
function code(){const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";let x="";for(let i=0;i<6;i++)x+=chars[Math.floor(Math.random()*chars.length)];return x;}
function formatRoomLabel(k,r){const title=r?.mcqTitle||r?.title||"MCQ Examination";const d=r?.createdAt?new Date(Number(r.createdAt)).toLocaleString("en-IN",{timeZone:"Asia/Kolkata",dateStyle:"short",timeStyle:"short"}):"";return `${k} — ${title}${d?` — ${d} IST`:""}`;}
async function refreshRooms(){if(!uid)return;const snap=await get(ref(db,"rooms"));const sel=$("existingRooms");sel.innerHTML='<option value="">Select a saved MCQ exam room</option>';const rows=[];if(snap.exists()){const all=snap.val()||{};Object.entries(all).forEach(([k,r])=>{if(r?.examType!=="mcq")return;if(!isAdmin(auth.currentUser)&&r?.hostUid!==uid)return;rows.push([k,r]);});}rows.sort((a,b)=>Number(b[1]?.createdAt||0)-Number(a[1]?.createdAt||0));rows.forEach(([k,r])=>{const o=document.createElement("option");o.value=k;o.textContent=formatRoomLabel(k,r);sel.appendChild(o);});msg(rows.length?`${rows.length} saved MCQ room${rows.length===1?"":"s"} available. Select one to load it.`:"No saved MCQ exam rooms found. Create a new room.",rows.length?"live":"");}
async function loadSelected(){const c=$("existingRooms").value;if(!c)return alert("Please select an existing MCQ exam room.");const s=await get(ref(db,`rooms/${c}`));if(!s.exists())return alert("That MCQ room could not be found.");const r=s.val();if(r.examType!=="mcq")return alert("Selected room is not an MCQ exam.");if(!isAdmin(auth.currentUser)&&r.hostUid!==uid)return alert("You do not have permission to load this room.");room=c;loadedRoomData=r;$("title").value=r.mcqTitle||r.title||"MCQ Examination";$("minutes").value=Math.max(1,Math.round(Number(r.mcqTimeSeconds||1800)/60));const qs=r.mcqQuestions||{};questions=Object.keys(qs).sort((a,b)=>Number(a.replace(/\D/g,""))-Number(b.replace(/\D/g,"")).map(k=>qs[k]);$("count").value=Math.max(1,questions.length||Number($("count").value||10));render();$("roomCode").textContent=room;$("setup").classList.remove("hidden");msg(`Existing MCQ room ${room} loaded. You can review or update the questions, then click Save MCQ Exam.` ,"live");}
async function create(){if(!uid)return alert("Please sign in as an approved host first.");if(!(await access(auth.currentUser)))return alert("Host permission is not approved.");resetEditor();const title=$("title").value.trim()||"MCQ Examination",minutes=Number($("minutes").value||30),count=Number($("count").value||10);if(minutes<1||count<1)return alert("Enter valid exam time and question count.");let c;do{c=code();}while((await get(ref(db,`rooms/${c}`))).exists());room=c;await set(ref(db,`rooms/${room}`),{hostUid:uid,title,examType:"mcq",mcqTitle:title,mcqTimeSeconds:minutes*60,mcqQuestions:{},createdAt:Date.now(),runDate:new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Kolkata"})});$("roomCode").textContent=room;$("setup").classList.remove("hidden");render();await refreshRooms();$("existingRooms").value=room;msg(`Room ${room} created. Enter all questions, then click Save MCQ Exam.` ,"live");}
async function save(){if(!room)return alert("Select an existing room or create a new MCQ room first.");const qs=collect();for(let i=0;i<qs.length;i++){if(!qs[i].text||Object.values(qs[i].options).some(v=>!v))return alert(`Please complete Question ${i+1}.`);}const obj={};qs.forEach((q,i)=>obj["q"+(i+1)]=q);await update(ref(db,`rooms/${room}`),{mcqTitle:$("title").value.trim()||"MCQ Examination",title:$("title").value.trim()||"MCQ Examination",mcqTimeSeconds:Number($("minutes").value||30)*60,mcqQuestions:obj,examType:"mcq",updatedAt:Date.now()});loadedRoomData=(await get(ref(db,`rooms/${room}`))).val();await refreshRooms();$("existingRooms").value=room;msg("MCQ Exam saved successfully. Participants can join with Room Code: "+room,"live");}
$("createBtn").onclick=create;$("loadBtn").onclick=loadSelected;$("refreshRoomsBtn").onclick=refreshRooms;$("saveBtn").onclick=save;$("count").onchange=render;$("backBtn").onclick=()=>location.href="host.html";
onAuthStateChanged(auth,async u=>{uid=u?.uid||null;$("authStatus").textContent=u?`Signed in: ${u.email}`:"Not signed in";if(!u){msg("Please sign in from Host Panel first.","blocked");$("createBtn").disabled=true;$("loadBtn").disabled=true;$("refreshRoomsBtn").disabled=true;$("saveBtn").disabled=true;}else if(!(await access(u))){msg("Host approval is required before creating or loading an MCQ exam.","blocked");$("createBtn").disabled=true;$("loadBtn").disabled=true;$("refreshRoomsBtn").disabled=true;$("saveBtn").disabled=true;}else{$("createBtn").disabled=false;$("loadBtn").disabled=false;$("refreshRoomsBtn").disabled=false;$("saveBtn").disabled=false;await refreshRooms();}});
