import { initializeApp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import { getAuth, onAuthStateChanged, createUserWithEmailAndPassword, signInWithEmailAndPassword, sendPasswordResetEmail, signOut, setPersistence, browserLocalPersistence, indexedDBLocalPersistence } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import { getDatabase, ref, set, update, get, serverTimestamp, remove } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-database.js";
import { firebaseConfig } from "./firebase-config.js";
const app=initializeApp(firebaseConfig), auth=getAuth(app), db=getDatabase(app);
async function ensureAuthPersistence(){
  try { await setPersistence(auth,browserLocalPersistence); return "local"; }
  catch(e) { try { await setPersistence(auth,indexedDBLocalPersistence); return "indexeddb"; } catch(e2) { console.warn("Auth persistence unavailable", e2); return "memory"; } }
}
const $=id=>document.getElementById(id);
const ADMIN_EMAIL="ramkrishnadevin.01@gmail.com";
let uid=null,currentUser=null,hostProfile=null;
function isAdmin(user=currentUser){return String(user?.email||"").toLowerCase()===ADMIN_EMAIL.toLowerCase();}
function isApproved(){return isAdmin()||hostProfile?.status==="approved";}
async function ensureHostProfile(user){if(!user)return null;const h=await get(ref(db,`hosts/${user.uid}`));return h.exists()?h.val():null;}
function profileComplete(p){return !!(p&&p.hostName&&p.designation&&p.placeOfPosting&&p.phone&&p.purpose&&p.purposeDetails);}
function fillHostProfileForm(p=hostProfile){if(!p)return;["Name","Designation","Place","Phone","PurposeDetails"].forEach(x=>{});if($("updateHostName"))$("updateHostName").value=p.hostName||"";if($("updateHostDesignation"))$("updateHostDesignation").value=p.designation||"";if($("updateHostPlace"))$("updateHostPlace").value=p.placeOfPosting||"";if($("updateHostPhone"))$("updateHostPhone").value=p.phone||"";if($("updateHostPurpose"))$("updateHostPurpose").value=p.purpose||"";if($("updateHostPurposeDetails"))$("updateHostPurposeDetails").value=p.purposeDetails||"";}
function msg(t,cls=""){const el=$("loginMsg");if(el){el.textContent=t;el.className=cls;}}
function clearHostRegistrationFields(){["hostName","hostDesignation","hostPlace","hostPhone","hostPurposeDetails","updateHostName","updateHostDesignation","updateHostPlace","updateHostPhone","updateHostPurposeDetails"].forEach(id=>{const el=$(id);if(el)el.value="";});["hostPurpose","updateHostPurpose"].forEach(id=>{const el=$(id);if(el)el.value="";});}
function openAdminModal(){if(!isAdmin())return;const m=$("adminModal");if(m){m.classList.remove("hidden");m.setAttribute("aria-hidden","false");}loadHostRequests();}
function closeAdminModal(){const m=$("adminModal");if(m){m.classList.add("hidden");m.setAttribute("aria-hidden","true");}}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));}
async function loadHostRequests(){if(!isAdmin())return;const body=$("hostRequests"),status=$("adminStatus");if(!body)return;try{const snap=await get(ref(db,"hosts"));const hosts=snap.val()||{};const arr=Object.entries(hosts).map(([id,h])=>({uid:id,...h})).sort((a,b)=>(Number(b.requestedAt)||0)-(Number(a.requestedAt)||0));status.textContent=`${arr.filter(x=>x.status==="pending").length} pending request(s).`;if(!arr.length){body.innerHTML='<tr><td colspan="9">No host requests.</td></tr>';return;}body.innerHTML=arr.map(h=>{const st=String(h.status||"pending").toUpperCase();let action="";if(h.uid!==uid){const opts=[];if(h.status==="pending"){opts.push('<option value="approved">Approve</option>','<option value="rejected">Reject</option>');}else if(h.status==="approved"){opts.push('<option value="revoked">Revoke</option>');}else{opts.push('<option value="approved">Approve</option>','<option value="rejected">Reject</option>');}opts.push('<option value="__delete__">Delete</option>');action=`<select class="hostActionSelect" data-uid="${esc(h.uid)}"><option value="">Select Action</option>${opts.join("")}</select>`;}const when=h.requestedAt?new Date(Number(h.requestedAt)).toLocaleString():"";const purpose=h.purpose?`${esc(h.purpose)}${h.purposeDetails?`<br><small>${esc(h.purposeDetails)}</small>`:""}`:"";return `<tr><td>${esc(h.email||"")}</td><td>${esc(h.hostName||"")}</td><td>${esc(h.designation||"")}</td><td>${esc(h.placeOfPosting||"")}</td><td>${esc(h.phone||"")}</td><td>${purpose}</td><td><span class="badge ${h.status==="approved"?'green':h.status==="pending"?'yellow':'red'}">${esc(st)}</span></td><td>${esc(when)}</td><td>${action||"—"}</td></tr>`;}).join("");document.querySelectorAll('.hostActionSelect').forEach(sel=>sel.onchange=async()=>{const action=sel.value,hostUid=sel.dataset.uid;if(!action)return;sel.value="";if(action==="__delete__")await deleteHostRequest(hostUid);else await setHostStatus(hostUid,action);});}catch(e){console.error(e);status.textContent=`Unable to load host requests: ${e.message||e}`;}}
async function setHostStatus(hostUid,status){if(!isAdmin()||!hostUid)return;const label=status==="approved"?"approve":status==="revoked"?"revoke":"reject";if(!confirm(`Are you sure you want to ${label} this host?`))return;await update(ref(db,`hosts/${hostUid}`),{status,reviewedAt:serverTimestamp(),reviewedBy:currentUser.uid});await loadHostRequests();}
async function deleteHostRequest(hostUid){if(!isAdmin()||!hostUid||hostUid===uid)return;if(!confirm("Delete this host request record? This removes the request from the Administrator portal but does not delete the login account."))return;await remove(ref(db,`hosts/${hostUid}`));await loadHostRequests();}
async function saveHostProfile(){if(!currentUser)return;const hostName=$("updateHostName").value.trim(),designation=$("updateHostDesignation").value.trim(),placeOfPosting=$("updateHostPlace").value.trim(),phone=$("updateHostPhone").value.trim(),purpose=$("updateHostPurpose").value,purposeDetails=$("updateHostPurposeDetails").value.trim(),out=$("hostProfileUpdateMsg");if(!hostName||!designation||!placeOfPosting||!phone||!purpose||!purposeDetails){if(out)out.textContent="Please fill in all required registration fields.";return;}if(!/^[0-9+()\- ]{7,15}$/.test(phone)){if(out)out.textContent="Please enter a valid phone number.";return;}try{const existing=hostProfile||{};const data={email:(currentUser.email||"").toLowerCase(),hostName,designation,placeOfPosting,phone,purpose,purposeDetails,status:existing.status||"pending",requestedAt:existing.requestedAt||Date.now(),updatedAt:serverTimestamp()};await update(ref(db,`hosts/${currentUser.uid}`),data);hostProfile={...existing,...data,updatedAt:Date.now(),requestedAt:existing.requestedAt||Date.now()};if(out)out.textContent="✓ Registration details saved. The Administrator can now review the complete information.";renderAccess();}catch(e){if(out)out.textContent=e.message||String(e);}}
function syncHostRoute(){const live=location.hash==="#liveQuiz";const menu=$("hostMenu"),app=$("hostApp");if(menu)menu.classList.toggle("hidden",live||!currentUser||!isApproved());if(app)app.classList.toggle("hidden",!live||!currentUser||!isApproved());const title=document.querySelector("header h1"),sub=document.querySelector("header small");if(title)title.textContent=live?"🏆 Live Quiz Competition — Host Panel":"🏆 Host Portal";if(sub)sub.textContent=live?"Live Quiz Control Centre":"Host Control Centre";}
function renderAccess(){const launcher=$("adminLauncher"),pageLauncher=$("adminPageLauncher"),access=$("hostAccessCard"),menu=$("hostMenu"),updateBox=$("hostProfileUpdate");if(launcher)launcher.classList.toggle("hidden",!isAdmin());if(pageLauncher)pageLauncher.classList.toggle("hidden",!isAdmin());if(!currentUser){if(menu)menu.classList.add("hidden");if($("hostApp"))$("hostApp").classList.add("hidden");if(access)access.classList.add("hidden");closeAdminModal();return;}if(isAdmin()){if(access)access.classList.add("hidden");syncHostRoute();return;}const approved=isApproved();if(access)access.classList.remove("hidden");if(access){const st=$("hostAccessStatus");if(!hostProfile)st.innerHTML="📝 <b>Host registration is incomplete.</b><br>Please complete your Host Registration details below. Your host request will be created only after you save the complete information.";else if(hostProfile.status==="pending")st.innerHTML="⏳ <b>Host permission is pending.</b><br>Your complete registration has been submitted. The Administrator must approve it before you can conduct a competition.";else if(hostProfile.status==="rejected"||hostProfile.status==="revoked")st.innerHTML="🚫 <b>Host permission is not active.</b><br>Please contact the Administrator.";else st.textContent="Host permission is active.";fillHostProfileForm();if(updateBox)updateBox.classList.toggle("hidden",!!hostProfile.status&&profileComplete(hostProfile));}syncHostRoute();}
$("signupBtn").onclick=()=>{$("registrationBox").classList.remove("hidden");$("signupBtn").classList.add("hidden");$("registrationSubmitBtn").classList.remove("hidden");$("registrationBox").scrollIntoView({behavior:"smooth",block:"center"});msg("Please complete all Host Registration details first. Your host account and host request will be created only after you submit the completed form.");};
$("registrationSubmitBtn").onclick=async()=>{try{const email=$("email").value.trim().toLowerCase(),password=$("password").value,hostName=$("hostName").value.trim(),designation=$("hostDesignation").value.trim(),placeOfPosting=$("hostPlace").value.trim(),phone=$("hostPhone").value.trim(),purpose=$("hostPurpose").value,purposeDetails=$("hostPurposeDetails").value.trim();if(!email||!password||!hostName||!designation||!placeOfPosting||!phone||!purpose||!purposeDetails){msg("Please fill in all required Host registration fields marked with *.");return;}if(password.length<6){msg("Password must be at least 6 characters.");return;}if(!/^[0-9+()\- ]{7,15}$/.test(phone)){msg("Please enter a valid phone number.");return;}$('registrationSubmitBtn').disabled=true;await ensureAuthPersistence();
  const cred=await createUserWithEmailAndPassword(auth,email,password);const profile={email,hostName,designation,placeOfPosting,phone,purpose,purposeDetails,status:isAdmin(cred.user)?"approved":"pending",requestedAt:serverTimestamp()};await set(ref(db,`hosts/${cred.user.uid}`),profile);hostProfile={...profile,requestedAt:Date.now()};msg(isAdmin(cred.user)?"Administrator account created and activated.":"Host registration submitted. Please wait for Administrator approval.");}catch(e){msg(e.message||String(e));$("registrationSubmitBtn").disabled=false;}};
$("loginBtn").onclick=async()=>{try{await ensureAuthPersistence();await signInWithEmailAndPassword(auth,$("email").value.trim(),$("password").value);}catch(e){msg(e.message)}};
$("forgotPasswordBtn").onclick=async()=>{try{const email=$("email").value.trim().toLowerCase();if(!email){msg("Please enter your registered email address in the Email box first.");$("email").focus();return;}await sendPasswordResetEmail(auth,email);msg("✓ Password reset link has been sent to your registered email address. Please check your Inbox and Spam/Junk folder.","success");}catch(e){const code=e?.code||"";if(code==="auth/user-not-found")msg("No Host account was found for this email address.");else if(code==="auth/invalid-email")msg("Please enter a valid email address.");else msg(e?.message||String(e));}};
$("homeLogoutBtn").onclick=async()=>{clearHostRegistrationFields();await signOut(auth);};$("pendingLogoutBtn").onclick=async()=>{clearHostRegistrationFields();await signOut(auth);};$("openAdminApprovalBtn").onclick=openAdminModal;$("openAdminPageBtn").onclick=()=>location.href="administrator.html";$("closeAdminApprovalBtn").onclick=closeAdminModal;$("backToMainBtn").onclick=closeAdminModal;$("saveHostProfileBtn").onclick=saveHostProfile;
$("openLiveQuizBtn").onclick=()=>{localStorage.setItem("hostPortalLastSection","liveQuiz");location.hash="liveQuiz";syncHostRoute();window.scrollTo({top:0,behavior:"smooth"});};$("openMcqBtn").onclick=()=>location.href="host-mcq.html";$("openGeneralBtn").onclick=()=>location.href="host-general.html";$("openOtherResultsBtn").onclick=()=>location.href="other-results.html";
$("openOtherResultsManageBtn").onclick=()=>location.href="other-results.html#manage";$("openMcqResultsBtn").onclick=()=>location.href="host-mcq-results.html";
onAuthStateChanged(auth,async user=>{currentUser=user||null;uid=user?.uid||null;$("authStatus").textContent=user?(isAdmin(user)?"Administrator signed in":"Signed in"):"Not signed in";$("loginCard").classList.toggle("hidden",!!user);if(!user){clearHostRegistrationFields();msg("");$("registrationBox").classList.add("hidden");$("signupBtn").classList.remove("hidden");$("registrationSubmitBtn").classList.remove("hidden");$("registrationSubmitBtn").disabled=false;$("hostMenu").classList.add("hidden");$("adminLauncher").classList.add("hidden");closeAdminModal();$("hostAccessCard").classList.add("hidden");return;}try{hostProfile=await ensureHostProfile(user);renderAccess();if(isAdmin(user))await loadHostRequests();}catch(e){console.error(e);msg(`Access check failed: ${e.message||e}`);}});

window.addEventListener("hashchange",()=>{if(typeof syncHostRoute==="function")syncHostRoute();});
