import { initializeApp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import { getDatabase, ref, get, set, update } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-database.js";
import { firebaseConfig } from "./firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getDatabase(app),$=id=>document.getElementById(id),ADMIN="ramkrishnadeinv.01@gmail.com";let uid=null,room="",questions=[];
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));}function msg(t,cls=""){$("msg").textContent=t;$("msg").className="status "+cls;}function isAdmin(u){return String(u?.email||"").toLowerCase()===ADMIN;}async function access(u){if(!u)return false;if(isAdmin(u))return true;const s=await get(ref(db,`hosts/${u.uid}`));return s.exists()&&s.val()?.status==="approved";}function code(){const c="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";let x="";for(let i=0;i<6;i++)x+=c[Math.floor(Math.random()*c.length)];return x;}function fmt(ts){if(!ts)return"—";return new Date(Number(ts)).toLocaleString("en-IN",{timeZone:"Asia/Kolkata",dateStyle:"medium",timeStyle:"short"})+" IST";}function st(r){return String(r?.examStatus||"NOT STARTED").toUpperCase();}
function render(){const n=Math.max(1,Math.min(100,Number($("count").value||10)));questions=Array.from({length:n},(_,i)=>questions[i]||{text:""});$("questions").innerHTML=questions.map((q,i)=>`<div class="qbox"><h3>Question ${i+1}</h3><div class="field"><label>Question *</label><textarea id="q_${i}" rows="5" style="width:100%;box-sizing:border-box">${esc(q.text)}</textarea></div></div>`).join("");}function collect(){return questions.map((_,i)=>({text:$("q_"+i).value.trim()}));}
async function refreshRooms(){const s=await get(ref(db,"rooms"));const sel=$("roomSelect");sel.innerHTML='<option value="">-- Select existing General Question room --</option>';if(s.exists())Object.entries(s.val()||{}).filter(([k,r])=>r&&r.examType==="general").sort((a,b)=>(b[1].createdAt||0)-(a[1].createdAt||0)).forEach(([k,r])=>{const o=document.createElement("option");o.value=k;o.textContent=`${k} — ${r.generalTitle||r.title||"General Exam"} — ${st(r)}`;sel.appendChild(o);});msg("General exam rooms refreshed.","live");}
async function loadRoom(){const c=$("roomSelect").value;if(!c)return alert("Please select a General Question room.");const s=await get(ref(db,`rooms/${c}`));if(!s.exists()||s.val().examType!=="general")return alert("General Question room not found.");const r=s.val();room=c;$("roomCode").textContent=room;$("setup").classList.remove("hidden");$("title").value=r.generalTitle||r.title||"General Question Based Exam";const qs=r.generalQuestions||{};questions=Object.keys(qs).sort((a,b)=>Number(a.slice(1))-Number(b.slice(1))).map(k=>qs[k]);$("count").value=questions.length||10;render();renderControl(r);msg(`Loaded room ${room}.`,"live");}
function renderControl(r){$("statusValue").textContent=st(r);$("scheduleInfo").textContent=r.scheduledStartAt?`Scheduled: ${fmt(r.scheduledStartAt)} | Duration: ${Math.round(Number(r.durationSeconds||0)/60)} min`:"No automatic schedule set.";$("manualStartBtn").disabled=["LIVE","CLOSED"].includes(st(r));$("scheduleBtn").disabled=["LIVE","CLOSED"].includes(st(r));$("cancelScheduleBtn").disabled=st(r)!=="SCHEDULED";$("closeExamBtn").disabled=st(r)!=="LIVE";}
async function create(){if(!uid||!(await access(auth.currentUser))){alert("Please sign in as an approved host first.");return;}const title=$("title").value.trim()||"General Question Based Exam",count=Number($("count").value||10);let c;do{c=code();}while((await get(ref(db,`rooms/${c}`))).exists());room=c;await set(ref(db,`rooms/${room}`),{hostUid:uid,title,examType:"general",generalTitle:title,generalQuestions:{},createdAt:Date.now(),runDate:new Date().toISOString().slice(0,10),examStatus:"NOT STARTED",startMode:"manual"});$("roomCode").textContent=room;$("setup").classList.remove("hidden");questions=[];render();renderControl({examStatus:"NOT STARTED"});await refreshRooms();msg(`Room ${room} created. Enter questions and save the exam.`,'live');}
async function save(){if(!room)return alert("Create or load a General Question room first.");const qs=collect();for(let i=0;i<qs.length;i++)if(!qs[i].text)return alert(`Please complete Question ${i+1}.`);await update(ref(db,`rooms/${room}`),{generalTitle:$("title").value.trim()||"General Question Based Exam",generalQuestions:Object.fromEntries(qs.map((q,i)=>[`q${i+1}`,q])),examType:"general",updatedAt:Date.now()});msg(`General Question Exam saved. Room Code: ${room}`,'live');await refreshRooms();}
async function start(){if(!room)return;const s=await get(ref(db,`rooms/${room}`));if(!s.exists())return;const r=s.val();if(["LIVE","CLOSED"].includes(st(r)))return alert("This exam cannot be started in its current status.");const now=Date.now();await update(ref(db,`rooms/${room}`),{examStatus:"LIVE",startMode:"manual",startedAt:now,scheduledStartAt:null,scheduledEndAt:null});renderControl({...r,examStatus:"LIVE"});msg("General Question exam is now LIVE.",'live');}
async function schedule(){if(!room)return alert("Select or create a room first.");const date=$("date").value,time=$("time").value,dur=Number($("duration").value||30);if(!date||!time||dur<1)return alert("Enter date, time and duration.");const start=new Date(`${date}T${time}:00+05:30`).getTime();if(start<=Date.now())return alert("Choose a future IST date and time.");const s=await get(ref(db,`rooms/${room}`));const r=s.val()||{};if(["LIVE","CLOSED"].includes(st(r)))return alert("This room cannot be scheduled in its current status.");const end=start+dur*60000;await update(ref(db,`rooms/${room}`),{examStatus:"SCHEDULED",startMode:"automatic",scheduledStartAt:start,scheduledEndAt:end,durationSeconds:dur*60});renderControl({...r,examStatus:"SCHEDULED",scheduledStartAt:start,durationSeconds:dur*60});msg(`Exam scheduled for ${fmt(start)}.`,'live');}
async function cancel(){if(!room)return;await update(ref(db,`rooms/${room}`),{examStatus:"NOT STARTED",startMode:"manual",scheduledStartAt:null,scheduledEndAt:null,durationSeconds:null});const s=await get(ref(db,`rooms/${room}`));renderControl(s.val());msg("Automatic schedule cancelled.",'live');}async function close(){if(!room)return;await update(ref(db,`rooms/${room}`),{examStatus:"CLOSED",closedAt:Date.now()});const s=await get(ref(db,`rooms/${room}`));renderControl(s.val());msg("General Question exam closed. Results are now frozen.",'live');}
async function poll(){if(!room)return;const s=await get(ref(db,`rooms/${room}`));if(!s.exists())return;const r=s.val(),now=Date.now();if(st(r)==="SCHEDULED"&&Number(r.scheduledStartAt)<=now){await update(ref(db,`rooms/${room}`),{examStatus:"LIVE",startedAt:Number(r.scheduledStartAt)});r.examStatus="LIVE";}if(st(r)==="LIVE"&&r.scheduledEndAt&&Number(r.scheduledEndAt)<=now){await update(ref(db,`rooms/${room}`),{examStatus:"CLOSED",closedAt:Number(r.scheduledEndAt)});r.examStatus="CLOSED";}renderControl(r);}
$("createBtn").onclick=create;$("saveBtn").onclick=save;$("count").onchange=render;$("refreshBtn").onclick=refreshRooms;$("loadBtn").onclick=loadRoom;$("backBtn").onclick=()=>location.href="host.html";$("manualStartBtn").onclick=start;$("scheduleBtn").onclick=schedule;$("cancelScheduleBtn").onclick=cancel;$("closeExamBtn").onclick=close;$("manualMode").onchange=()=>setMode();$("autoMode").onchange=()=>setMode();function setMode(){const a=$("autoMode").checked;$("scheduleBox").classList.toggle("hidden",!a);$("manualStartBtn").classList.toggle("hidden",a);$("scheduleBtn").classList.toggle("hidden",!a);}setMode();setInterval(poll,5000);
onAuthStateChanged(auth,async u=>{uid=u?.uid||null;$("authStatus").textContent=u?`Signed in: ${u.email}`:"Not signed in";if(!u||!(await access(u))){msg("Host approval is required before managing General Question exams.","blocked");$("createBtn").disabled=true;$("refreshBtn").disabled=true;$("loadBtn").disabled=true;}else{await refreshRooms();msg("Approved host. Select an existing room or create a new General Question exam.",'live');}});
