import { initializeApp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import { getDatabase, ref, get, set, update, remove } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-database.js";
import { firebaseConfig } from "./firebase-config.js";

const app=initializeApp(firebaseConfig), auth=getAuth(app), db=getDatabase(app);
const $=id=>document.getElementById(id), ADMIN="ramkrishnadevinv.01@gmail.com";
let uid=null, room="", questions=[];
const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;"," ":"&gt;","\"":"&quot;","'":"&#39;"}[m]));}
function msg(t,cls=""){ $("msg").textContent=t; $("msg").className="status "+cls; }
function isAdmin(u){return String(u?.email||"").toLowerCase()===ADMIN;}
async function access(u){if(!u)return false;if(isAdmin(u))return true;const s=await get(ref(db,`hosts/${u.uid}`));return s.exists()&&s.val()?.status==="approved";}
function code(){let x="";for(let i=0;i<6;i++)x+=chars[Math.floor(Math.random()*chars.length)];return x;}
function renderQuestions(){const n=Math.max(1,Math.min(100,Number($("count").value||10)));questions=Array.from({length:n},(_,i)=>questions[i]||{text:"",options:{A:"",B:"",C:"",D:""},correct:"A"});$("questions").innerHTML=questions.map((q,i)=>`<div class="qbox"><h3>Question ${i+1}</h3><div class="field"><label>Question *</label><textarea id="q_${i}" rows="3" style="width:100%;box-sizing:border-box">${esc(q.text)}</textarea></div><div class="qgrid"><div class="field"><label>A *</label><input id="a_${i}" value="${esc(q.options.A)}"></div><div class="field"><label>B *</label><input id="b_${i}" value="${esc(q.options.B)}"></div><div class="field"><label>C *</label><input id="c_${i}" value="${esc(q.options.C)}"></div><div class="field"><label>D *</label><input id="d_${i}" value="${esc(q.options.D)}"></div><div class="field"><label>Correct Answer *</label><select id="cans_${i}"><option>A</option><option>B</option><option>C</option><option>D</option></select></div></div></div>`).join("");questions.forEach((q,i)=>$("cans_"+i).value=q.correct||"A");}
function collect(){return questions.map((_,i)=>({text:$("q_"+i).value.trim(),options:{A:$("a_"+i).value.trim(),B:$("b_"+i).value.trim(),C:$("c_"+i).value.trim(),D:$("d_"+i).value.trim()},correct:$("cans_"+i).value}));}
function fmt(ts){if(!ts)return "—";return new Date(Number(ts)).toLocaleString("en-IN",{timeZone:"Asia/Kolkata",dateStyle:"medium",timeStyle:"short"})+" IST";}
function setModeUI(){const auto=$("autoMode").checked;$("scheduleBox").classList.toggle("hidden",!auto);$("manualStartBtn").classList.toggle("hidden",auto);$("scheduleBtn").classList.toggle("hidden",!auto);}
function statusText(r){return String(r?.examStatus||"NOT STARTED").toUpperCase();}
async function refreshRooms(){const snap=await get(ref(db,"rooms"));const sel=$("roomSelect");sel.innerHTML='<option value="">-- Select existing MCQ room --</option>';if(snap.exists()){const rooms=snap.val()||{};Object.entries(rooms).filter(([k,r])=>r&&r.examType==="mcq").sort((a,b)=>(b[1].createdAt||0)-(a[1].createdAt||0)).forEach(([k,r])=>{const o=document.createElement("option");o.value=k;o.textContent=`${k} — ${r.mcqTitle||r.title||"MCQ Exam"} — ${statusText(r)}`;sel.appendChild(o);});}msg("MCQ rooms refreshed.","live");}
async function loadRoom(){const c=$("roomSelect").value;if(!c){alert("Please select an MCQ room.");return;}const s=await get(ref(db,`rooms/${c}`));if(!s.exists()){alert("Room not found.");return;}const r=s.val();if(r.examType!=="mcq"){alert("This is not an MCQ room.");return;}room=c;$("roomCode").textContent=room;$("setup").classList.remove("hidden");$("title").value=r.mcqTitle||r.title||"MCQ Examination";$("minutes").value=Math.max(1,Math.round(Number(r.mcqTimeSeconds||1800)/60));const qs=r.mcqQuestions||{};questions=Object.keys(qs).sort((a,b)=>Number(a.slice(1))-Number(b.slice(1))).map(k=>qs[k]);$("count").value=questions.length||10;renderQuestions();renderControl(r);msg(`Loaded room ${room}.`,"live");}
function renderControl(r){$("statusValue").textContent=statusText(r);$("scheduleInfo").textContent=r.scheduledStartAt?`Scheduled: ${fmt(r.scheduledStartAt)} | Duration: ${Math.round(Number(r.durationSeconds||r.mcqTimeSeconds||0)/60)} min`:"No automatic schedule set.";$("manualStartBtn").disabled=["LIVE","CLOSED"].includes(statusText(r));$("scheduleBtn").disabled=["LIVE","CLOSED"].includes(statusText(r));$("cancelScheduleBtn").disabled=statusText(r)!=="SCHEDULED";$("closeExamBtn").disabled=statusText(r)!=="LIVE";}
async function create(){if(!uid||!(await access(auth.currentUser))){alert("Please sign in as an approved host first.");return;}const title=$("title").value.trim()||"MCQ Examination",minutes=Number($("minutes").value||30),count=Number($("count").value||10);let c;do{c=code();}while((await get(ref(db,`rooms/${c}`))).exists());room=c;await set(ref(db,`rooms/${room}`),{hostUid:uid,title,examType:"mcq",mcqTitle:title,mcqTimeSeconds:minutes*60,mcqQuestions:{},createdAt:Date.now(),runDate:new Date().toISOString().slice(0,10),examStatus:"NOT STARTED",startMode:"manual"});$("roomCode").textContent=room;$("setup").classList.remove("hidden");questions=[];renderQuestions();renderControl({examStatus:"NOT STARTED",mcqTimeSeconds:minutes*60});await refreshRooms();msg(`Room ${room} created. Enter questions and save the exam.`,`live`);}
async function save(){if(!room){alert("Create or load an MCQ room first.");return;}const qs=collect();for(let i=0;i<qs.length;i++)if(!qs[i].text||Object.values(qs[i].options).some(v=>!v)){alert(`Please complete Question ${i+1}.`);return;}const minutes=Number($("minutes").value||30);await update(ref(db,`rooms/${room}`),{mcqTitle:$("title").value.trim()||"MCQ Examination",mcqTimeSeconds:minutes*60,mcqQuestions:Object.fromEntries(qs.map((q,i)=>[`q${i+1}`,q])),examType:"mcq",updatedAt:Date.now()});msg(`MCQ Exam saved. Room Code: ${room}`,"live");await refreshRooms();}
async function startManual(){if(!room)return;const s=await get(ref(db,`rooms/${room}`));if(!s.exists())return;const r=s.val();if(["LIVE","CLOSED"].includes(statusText(r))){alert("This exam cannot be started in its current status.");return;}const now=Date.now();await update(ref(db,`rooms/${room}`),{examStatus:"LIVE",startMode:"manual",startedAt:now,scheduledStartAt:null,scheduledEndAt:null});renderControl({...r,examStatus:"LIVE",startedAt:now});msg("MCQ exam is now LIVE.","live");}
async function schedule(){if(!room)return alert("Select or create a room first.");const date=$("date").value,time=$("time").value,dur=Number($("duration").value||30);if(!date||!time||dur<1)return alert("Enter date, time and duration.");const start=new Date(`${date}T${time}:00+05:30`).getTime();if(start<=Date.now())return alert("Choose a future IST date and time.");const s=await get(ref(db,`rooms/${room}`));const r=s.val()||{};if(["SCHEDULED","LIVE","CLOSED"].includes(statusText(r))&&statusText(r)!=="SCHEDULED")return alert("This room cannot be scheduled in its current status.");const end=start+dur*60000;await update(ref(db,`rooms/${room}`),{examStatus:"SCHEDULED",startMode:"automatic",scheduledStartAt:start,scheduledEndAt:end,durationSeconds:dur*60});renderControl({...r,examStatus:"SCHEDULED",scheduledStartAt:start,durationSeconds:dur*60});msg(`Exam scheduled for ${fmt(start)}.`,"live");}
async function cancelSchedule(){if(!room)return;const s=await get(ref(db,`rooms/${room}`));if(!s.exists())return;await update(ref(db,`rooms/${room}`),{examStatus:"NOT STARTED",startMode:"manual",scheduledStartAt:null,scheduledEndAt:null,durationSeconds:null});renderControl({...s.val(),examStatus:"NOT STARTED"});msg("Automatic schedule cancelled.","live");}
async function closeExam(){if(!room)return;await update(ref(db,`rooms/${room}`),{examStatus:"CLOSED",closedAt:Date.now()});const s=await get(ref(db,`rooms/${room}`));renderControl(s.val());msg("MCQ exam closed. Results are now frozen.","live");}
async function poll(){if(!room)return;const s=await get(ref(db,`rooms/${room}`));if(!s.exists())return;const r=s.val(),now=Date.now();if(statusText(r)==="SCHEDULED"&&Number(r.scheduledStartAt)<=now){await update(ref(db,`rooms/${room}`),{examStatus:"LIVE",startedAt:Number(r.scheduledStartAt)});r.examStatus="LIVE";r.startedAt=Number(r.scheduledStartAt);}if(statusText(r)==="LIVE"&&r.scheduledEndAt&&Number(r.scheduledEndAt)<=now){await update(ref(db,`rooms/${room}`),{examStatus:"CLOSED",closedAt:Number(r.scheduledEndAt)});r.examStatus="CLOSED";}renderControl(r);}
$("createBtn").onclick=create;$("saveBtn").onclick=save;$("count").onchange=renderQuestions;$("refreshBtn").onclick=refreshRooms;$("loadBtn").onclick=loadRoom;$("backBtn").onclick=()=>location.href="host.html";$("manualStartBtn").onclick=startManual;$("scheduleBtn").onclick=schedule;$("cancelScheduleBtn").onclick=cancelSchedule;$("closeExamBtn").onclick=closeExam;$("manualMode").onchange=setModeUI;$("autoMode").onchange=setModeUI;setModeUI();setInterval(poll,5000);
onAuthStateChanged(auth,async u=>{uid=u?.uid||null;$("authStatus").textContent=u?`Signed in: ${u.email}`:"Not signed in";if(!u||!(await access(u))){msg("Host approval is required before managing MCQ exams.","blocked");$("createBtn").disabled=true;$("refreshBtn").disabled=true;$("loadBtn").disabled=true;}else{await refreshRooms();msg("Approved host. Select an existing room or create a new MCQ exam.","live");}});
