import { initializeApp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import { getDatabase,ref,get,update,serverTimestamp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-database.js";
import { firebaseConfig } from "./firebase-config.js";
const app=initializeApp(firebaseConfig),db=getDatabase(app),$=id=>document.getElementById(id);
const params=new URLSearchParams(location.search);const room=(params.get("room")||sessionStorage.getItem("mcqRoom")||"").toUpperCase();const participant=JSON.parse(sessionStorage.getItem("quizParticipant")||"null");let questions=[],idx=0,selected="",answers={},timer=null,endAt=0;
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
async function init(){if(!participant||!/^[A-Z0-9]{6}$/.test(room)){return showError("Participant details or room code are missing.");}const snap=await get(ref(db,`rooms/${room}`));if(!snap.exists())return showError("Room not found.");const r=snap.val()||{};$("roomCode").textContent=room;$("examTitle").textContent=r.mcqTitle||"MCQ Examination";const qObj=r.mcqQuestions||{};questions=Object.keys(qObj).sort((a,b)=>Number((a.match(/\d+/)||[0])[0])-Number((b.match(/\d+/)||[0])[0])).map(k=>({id:k,...qObj[k]}));if(!questions.length)return showError("No MCQ questions have been configured for this room yet.");const seconds=Number(r.mcqTimeSeconds||0);if(seconds>0){endAt=Date.now()+seconds*1000;tick();timer=setInterval(tick,250);}showQuestion();}
function showError(t){$("status").className="status blocked";$("status").textContent=t;$("question").textContent="";$("options").innerHTML="";$("nextBtn").disabled=true;}
function tick(){const left=Math.max(0,endAt-Date.now());const sec=Math.ceil(left/1000);$("timer").textContent=`${String(Math.floor(sec/60)).padStart(2,"0")}:${String(sec%60).padStart(2,"0")}`;if(left<=0){clearInterval(timer);finish(true);}}
function showQuestion(){const q=questions[idx];selected=answers[q.id]||"";$("qNo").textContent=`Question ${idx+1} of ${questions.length}`;$("question").innerHTML=esc(q.text||"");const opts=q.options||{};$("options").innerHTML=["A","B","C","D"].map(o=>`<button class="mcq-option ${selected===o?"selected":""}" data-o="${o}"><b>${o}.</b> ${esc(opts[o]||"")}</button>`).join("");document.querySelectorAll(".mcq-option").forEach(b=>b.onclick=()=>{selected=b.dataset.o;answers[q.id]=selected;document.querySelectorAll(".mcq-option").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");$("nextBtn").disabled=false;});$("nextBtn").disabled=!selected;$("nextBtn").textContent=idx===questions.length-1?"REVIEW / SUBMIT":"NEXT";}
async function finish(auto=false){clearInterval(timer);$("nextBtn").disabled=true;const key=participant.phone.replace(/\D/g,"");const payload={name:participant.name,designation:participant.designation,placeOfPosting:participant.placeOfPosting,phone:participant.phone,answers,submittedAt:serverTimestamp(),autoSubmitted:!!auto};await update(ref(db,`rooms/${room}/mcqAnswers/${key}`),payload);let correct=0;questions.forEach(q=>{if(answers[q.id]&&answers[q.id]===q.correct)correct++;});$("status").className="status live";$("status").textContent=`Exam submitted. Correct answers: ${correct} / ${questions.length}.`;$("message").innerHTML=`<div class="successbox">Your MCQ examination has been submitted.</div>`;$("options").innerHTML="";$("finishBtnWrap").classList.add("hidden");}
$("nextBtn").onclick=()=>{if(idx<questions.length-1){idx++;showQuestion();}else finish(false);};$("finishBtn")?.addEventListener("click",()=>finish(false));$("backBtn").onclick=()=>location.href="student.html";init();